### ISSUE TITLE
Cannot load Example1 file in M1 Mac

### ISSUE THREAD

**Issue by lopezchau** [lorifranke/SlicerTMS#15]
I am using Slicer 5.6.2 r32448, and Slicer TMS 1.1

The server is running normally, Slicer is running normally until the click on "Welcome to Slicer" drop down menu and click on "Slicer TMS Module"

I get this on the terminal.  I hope it helps to fix the bug.
<img width="946" alt="Captura de pantalla 2024-06-10 a la(s) 10 12 40 p  m" src="https://github.com/lorifranke/SlicerTMS/assets/143896040/5df3e28e-c0d1-4444-af20-8f92b90c0960">

**Comment by lopezchau** [comment]
This is the message in the error log of Slicer.

<img width="509" alt="Captura de pantalla 2024-06-10 a la(s) 10 19 52 p  m" src="https://github.com/lorifranke/SlicerTMS/assets/143896040/64a78d97-2c07-401c-9938-c2e8a02cc5fd">

**Comment by lorifranke** [comment]
@lopezchau Thanks for testing it on your end! 

First, I am not sure why this error is happening but it might be that the model.pth file is damaged. You can try to download it here and replace it locally in your Example 1 folder: https://drive.google.com/drive/folders/1CTpOg5XI-q4w8WA840g5DfrlXLng1AuX?usp=sharing

For the second issue: If you updated the Slicer version, did you again install all the extensions? Specifically slicerdmri which might be related to the tractographydisplay. If you open 3D Slicer and type in the Python console `slicer.modules.tractographydisplay.widgetRepresentation().activateWindow()` does it show the same error?

**Comment by lopezchau** [comment]
> @lopezchau Thanks for testing it on your end!
> 
> First, I am not sure why this error is happening but it might be that the model.pth file is damaged. You can try to download it here and replace it locally in your Example 1 folder: https://drive.google.com/drive/folders/1CTpOg5XI-q4w8WA840g5DfrlXLng1AuX?usp=sharing
> 
> For the second issue: If you updated the Slicer version, did you again install all the extensions? Specifically slicerdmri which might be related to the tractographydisplay. If you open 3D Slicer and type in the Python console `slicer.modules.tractographydisplay.widgetRepresentation().activateWindow()` does it show the same error?

Thanks to you for all your fantastic work! My pleasure to help in anything I can to test it on M1 Mac

It worked! 
Now I am getting stuck here...  Does it seems to you that fibers.vtk is also corrupted?  How much is the size of the full Example1 folder?
<img width="1508" alt="Captura de pantalla 2024-06-12 a la(s) 10 54 28 p  m" src="https://github.com/lorifranke/SlicerTMS/assets/143896040/9e63f4af-d8af-409b-9da6-0f107730cd77">

<img width="510" alt="Captura de pantalla 2024-06-12 a la(s) 10 56 02 p  m" src="https://github.com/lorifranke/SlicerTMS/assets/143896040/4e72da9f-4d83-4663-832c-8460e95092d7">

**Comment by lorifranke** [comment]
@lopezchau Yes, looks like github somehow compresses the files! The actual fibers file is 72.6 MB and in your folder there is only a 133byte file. The issue mainly happens when I try to upload files to github - they do not allow me to upload larger files (except when I buy one of their packages🙄). 
I have added them to the google drive from before as well to download (https://drive.google.com/drive/folders/1CTpOg5XI-q4w8WA840g5DfrlXLng1AuX?usp=sharing)
Please let me know if it works 😊

**Comment by lopezchau** [comment]
> @lopezchau Yes, looks like github somehow compresses the files and they get damaged! The actual fibers file is 72.6 MB and in your folder there is only a 133byte file. The issue mainly happens when I try to upload files to github - they do not allow me to upload larger files (except when I buy one of their packages🙄). I have added the fibers and skin files to the google drive from before as well to download (https://drive.google.com/drive/folders/1CTpOg5XI-q4w8WA840g5DfrlXLng1AuX?usp=sharing) Please let me know if it works 😊

Thank you!

**Comment by lopezchau** [comment]
Issue solved by downloading the files (links in this thread)  that are corrupted in GitHub
